In [2]:
# TODO:
# importing libraries
# Load the data
# How many fraudulent transactions?
# Summary statistics on amount column
# Create isPayment field
# Create isMovement field
# Create accountDiff field
# Create features and label variables
# Split dataset
# Normalize the features variables
# Fit the model to the training data
# Score the model on the training data
# Score the model on the test data
# Print the model coefficients

# New transaction data
# transaction1 = np.array([123456.78, 0.0, 1.0, 54670.1])
# transaction2 = np.array([98765.43, 1.0, 0.0, 8524.75])
# transaction3 = np.array([543678.31, 1.0, 0.0, 510025.5])

# Create a new transaction
# Combine new transactions into a single array
# Normalize the new transactions
# Predict fraud on the new transactions
# Show probabilities on the new transactions

In [3]:
# importing libraries
import seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
# Load the data
transactions = pd.read_csv('transactions_modified.csv')
transactions.head()

step      type      amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0   206  CASH_OUT    62927.08   C473782114           0.00            0.00   
1   380   PAYMENT    32851.57  C1915112886           0.00            0.00   
2   570  CASH_OUT  1131750.38  C1396198422     1131750.38            0.00   
3   184  CASH_OUT    60519.74   C982551468       60519.74            0.00   
4   162   CASH_IN    46716.01  C1759889425     7668050.60      7714766.61   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isPayment  \
0  C2096898696       649420.67       712347.75        0          0   
1   M916879292            0.00            0.00        0          1   
2  C1612235515       313070.53      1444820.92        1          0   
3  C1378644910        54295.32       182654.50        1          0   
4  C2059152908      2125468.75      2078752.75        0          0   

   isMovement  accountDiff  
0           1    649420.67  
1           0         0.00  
2           1    818679.85  
3           1      6224.42  
4           0   5542581.85

In [5]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            1000 non-null   int64  
 1   type            1000 non-null   object 
 2   amount          1000 non-null   float64
 3   nameOrig        1000 non-null   object 
 4   oldbalanceOrg   1000 non-null   float64
 5   newbalanceOrig  1000 non-null   float64
 6   nameDest        1000 non-null   object 
 7   oldbalanceDest  1000 non-null   float64
 8   newbalanceDest  1000 non-null   float64
 9   isFraud         1000 non-null   int64  
 10  isPayment       1000 non-null   int64  
 11  isMovement      1000 non-null   int64  
 12  accountDiff     1000 non-null   float64
dtypes: float64(6), int64(4), object(3)
memory usage: 101.7+ KB


In [10]:
# How many fraudulent transactions?
transactions.isFraud.value_counts()
# There are 282 fraudulent transactions

0    718
1    282
Name: isFraud, dtype: int64

In [11]:
# Summary statistics on amount column
transactions.amount.describe()

count    1.000000e+03
mean     5.373080e+05
std      1.423692e+06
min      0.000000e+00
25%      2.933705e+04
50%      1.265305e+05
75%      3.010378e+05
max      1.000000e+07
Name: amount, dtype: float64

In [12]:
# Create isPayment field

transactions.isPayment = transactions.type.apply(
lambda x:
    1 if x == 'PAYMENT' or x == 'DEBIT' else 0
)
transactions.head(10)

step      type      amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0   206  CASH_OUT    62927.08   C473782114           0.00            0.00   
1   380   PAYMENT    32851.57  C1915112886           0.00            0.00   
2   570  CASH_OUT  1131750.38  C1396198422     1131750.38            0.00   
3   184  CASH_OUT    60519.74   C982551468       60519.74            0.00   
4   162   CASH_IN    46716.01  C1759889425     7668050.60      7714766.61   
5   350   PAYMENT    16013.85  C2093859850       72766.00        56752.15   
6   306  CASH_OUT   277310.34  C1480259234           0.00            0.00   
7   332  CASH_OUT   184157.68   C399464792      188588.19         4430.51   
8   330   CASH_IN   136804.02   C304503510       20781.00       157585.02   
9   259   CASH_IN    60609.99  C2089244493     2907876.74      2968486.73   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isPayment  \
0  C2096898696       649420.67       712347.75        0          0   
1   M916879292            0.00            0.00        0          1   
2  C1612235515       313070.53      1444820.92        1          0   
3  C1378644910        54295.32       182654.50        1          0   
4  C2059152908      2125468.75      2078752.75        0          0   
5  M1803659246            0.00            0.00        0          1   
6   C410033330     13379400.65     13656710.99        0          0   
7   C295235726       358753.74       542911.42        0          0   
8  C1682763714       707549.54       570745.52        0          0   
9   C277506714       823473.00       762863.01        0          0   

   isMovement  accountDiff  
0           1    649420.67  
1           0         0.00  
2           1    818679.85  
3           1      6224.42  
4           0   5542581.85  
5           0     72766.00  
6           1  13379400.65  
7           1    170165.55  
8           0    686768.54  
9           0   2084403.74

In [13]:
# Create isMovement field
transactions.isMovement = transactions.type.apply(
lambda x:
    1 if x == 'CASH_OUT' or x == 'TRANSFER' else 0
)
transactions.head(10)

step      type      amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0   206  CASH_OUT    62927.08   C473782114           0.00            0.00   
1   380   PAYMENT    32851.57  C1915112886           0.00            0.00   
2   570  CASH_OUT  1131750.38  C1396198422     1131750.38            0.00   
3   184  CASH_OUT    60519.74   C982551468       60519.74            0.00   
4   162   CASH_IN    46716.01  C1759889425     7668050.60      7714766.61   
5   350   PAYMENT    16013.85  C2093859850       72766.00        56752.15   
6   306  CASH_OUT   277310.34  C1480259234           0.00            0.00   
7   332  CASH_OUT   184157.68   C399464792      188588.19         4430.51   
8   330   CASH_IN   136804.02   C304503510       20781.00       157585.02   
9   259   CASH_IN    60609.99  C2089244493     2907876.74      2968486.73   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isPayment  \
0  C2096898696       649420.67       712347.75        0          0   
1   M916879292            0.00            0.00        0          1   
2  C1612235515       313070.53      1444820.92        1          0   
3  C1378644910        54295.32       182654.50        1          0   
4  C2059152908      2125468.75      2078752.75        0          0   
5  M1803659246            0.00            0.00        0          1   
6   C410033330     13379400.65     13656710.99        0          0   
7   C295235726       358753.74       542911.42        0          0   
8  C1682763714       707549.54       570745.52        0          0   
9   C277506714       823473.00       762863.01        0          0   

   isMovement  accountDiff  
0           1    649420.67  
1           0         0.00  
2           1    818679.85  
3           1      6224.42  
4           0   5542581.85  
5           0     72766.00  
6           1  13379400.65  
7           1    170165.55  
8           0    686768.54  
9           0   2084403.74

In [15]:
# Create accountDiff field
transactions.accountDiff = abs(transactions.oldbalanceOrg - transactions.oldbalanceDest)

In [21]:
# Create features and label variables
features = transactions[['amount', 'isPayment', 'isMovement', 'accountDiff']]
features[:5]

amount  isPayment  isMovement  accountDiff
0    62927.08          0           1    649420.67
1    32851.57          1           0         0.00
2  1131750.38          0           1    818679.85
3    60519.74          0           1      6224.42
4    46716.01          0           0   5542581.85

In [22]:
label = transactions.isFraud
label[:3]

0    0
1    0
2    1
Name: isFraud, dtype: int64

In [23]:
# Split dataset
X_train, X_test, y_train, y_test = train_test_split(features,label, test_size=0.3, shuffle=True, random_state=42)

In [25]:
# Normalize the features variables
scaler = StandardScaler()
X_train_norm = scaler.fit_transform(X_train)
X_test_norm = scaler.transform(X_test)

In [26]:
# Fit the model to the training data
model = LogisticRegression()
model.fit(X_train_norm, y_train)

LogisticRegression()

In [30]:
# Score the model on the training data
model.score(X_train_norm, y_train)

0.8385714285714285

In [31]:
# Score the model on the test data
model.score(X_test_norm, y_test)

0.85

In [33]:
# Print the model coefficients
print(model.coef_, model.intercept_)
# We can verify amount is the most important feature and isPayment the less important.

[[ 2.42332129 -0.61723954  2.09324864 -0.99197343]] [-2.29616947]


In [39]:
# New transaction data
transaction1 = np.array([123456.78, 0.0, 1.0, 54670.1])
transaction2 = np.array([98765.43, 1.0, 0.0, 8524.75])
transaction3 = np.array([543678.31, 1.0, 0.0, 510025.5])
# Create a new transaction
your_transaction = np.array([200000.0, 0.0, 1.0, 3456.78])

In [42]:
# Combine new transactions into a single array
sample_transactions = np.stack((transaction1, transaction2, transaction3, your_transaction))
# Normalize the new transactions
sample_transactions = scaler.transform(sample_transactions)
sample_transactions

/home/joelinux/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.27885917, -0.53550416,  0.81892881, -0.46978056],
       [-0.29594918,  1.86739912, -1.22110737, -0.48268021],
       [ 0.01199527,  1.86739912, -1.22110737, -0.34248879],
       [-0.22588013, -0.53550416,  0.81892881, -0.48409692]])

In [43]:
# Predict fraud on the new transaction
model.predict(sample_transactions)

array([0, 0, 0, 0])

In [45]:
# Show probabilities on the new transactions
model.predict_proba(sample_transactions)

array([[0.61329147, 0.38670853],
       [0.99806026, 0.00193974],
       [0.99644584, 0.00355416],
       [0.57897872, 0.42102128]])